name: url-shortener-dev
services:
  db:
    image: mysql:9.1.0
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "${DB_PORT}:3306"
    networks:
      - server-side
      - db-client
    volumes:
      - .data/mysql:/var/lib/mysql

  db-client:
    depends_on:
      - db
    image: phpmyadmin:5.2.1
    restart: unless-stopped
    environment:
      PMA_HOST: db
    ports:
      - "${DB_CLIENT_PORT}:80"
    networks:
      - server-side
      - db-client

  frontend:
    build:
      context: frontend
      dockerfile: docker/Dockerfile.dev
    networks:
      - client-side
    ports:
      - ${FRONTEND_PORT}:5173
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: frontend
          target: /app
          ignore:
            - frontend/node_modules/
        - action: rebuild
          path: frontend/package.json

  backend:
    build:
      context: backend
      dockerfile: docker/Dockerfile.dev
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:3000
    restart: unless-stopped
    networks:
      - client-side
      - server-side
    develop:
      watch:
        - action: sync
          path: backend
          target: /app
          ignore:
            - backend/node_modules/
        - action: rebuild
          path: backend/package.json
        - action: rebuild
          path: .env

networks:
  client-side: {}
  server-side: {}
  db-client: {}
